### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by fakership** [wyvernnot/qiniu-webpack-plugin#5]
你好，发现了一个报错，当我注释掉你们的插件的时候，不会有问题，报错如下:
![image](https://cloud.githubusercontent.com/assets/16553183/23538519/c603fc24-000e-11e7-8efd-f3ac14673cd8.png)

**Comment by XmYellow** [comment]
你解决了？我是Ubuntu 16
 { RequestError: socket hang up
       at createHangUpError (_http_client.js:253:15)
       at Socket.socketOnEnd (_http_client.js:345:23)
       at emitNone (events.js:91:20)
       at Socket.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET', name: 'RequestError' } } +2m
  app:bin:compile Compiler encountered an error. { code: -1,

**Comment by XmYellow** [comment]
你解决了？我是Ubuntu 16
```
{ RequestError: socket hang up
at createHangUpError (_http_client.js:253:15)
at Socket.socketOnEnd (_http_client.js:345:23)
at emitNone (events.js:91:20)
at Socket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET', name: 'RequestError' } } +2m
app:bin:compile Compiler encountered an error. { code: -1,
```

**Comment by li2go** [comment]
[hash] 在使用htmlWebpackpulgin的时候会冲突。。。

**Comment by ufo22940268** [comment]
这个问题确实是因为七牛上传有限制导致的。

原来代码里面上传是并发进行了，如果改成顺序执行就可以解决这个问题。

可以参见我的修改: https://github.com/ufo22940268/qiniu-webpack-plugin/commit/2f8c76d741aba0791659685c3e32809cdc29441a
